language: ruby
rvm:
  - jruby-18mode
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
before_install:
  - sudo add-apt-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner" -y
  - sudo apt-get update -y
  - sudo apt-get install acroread ghostscript -y
